name: 'Engineering metrics collector'
description: 'Collects engineering metrics and uploads them to BigQuery'

runs:
  using: 'node20'
  main: 'src/index.js'

branding:
  icon: 'clock'
  color: 'blue'
