name: Collect engineering metrics

on:
  schedule:
    - cron: '0 9 * * *'  # Run at 4am CDT (9am UTC)
  workflow_dispatch:      # Allow manual triggering

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: '20.18.1'
          cache: 'npm'
          cache-dependency-path: .github/actions/eng-metrics/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: .github/actions/eng-metrics

      - name: Create service account key file
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > service-account-key.json
          # Verify the file is valid JSON
          cat service-account-key.json | jq . > /dev/null

      - name: Collect and upload metrics
        uses: ./.github/actions/eng-metrics
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: './config.json'
          bigquery-project: ${{ secrets.BIGQUERY_PROJECT_ID }}
          bigquery-dataset: 'github_metrics'
          bigquery-table: 'first_review'
          target-branch: 'main'
          lookback-days: '5'
          print-only: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
          SERVICE_ACCOUNT_KEY_PATH: './service-account-key.json'
